@baseurl = http://localhost:3333

@authToken = {{authenticate.response.body.access_token}}


# @name get_details_operator
GET {{baseurl}}/me
Authorization: Bearer {{authToken}}

###


# @name validate_token
GET {{baseurl}}/validate-token
Content-Type: application/json                        
Authorization: Bearer {{authToken}}

###

# @name create_account
POST {{baseurl}}/accounts
Content-Type: application/json

{
  "name": "fulano de tal",
  "email": "yurisousaenfer@gmail.com",
  "password": "12345678",
  "institutionsIds": ["1f9d3757-3eb7-4c0f-974b-f59e38b9dc75"]
}

###

# @name authenticate
POST {{baseurl}}/sessions
Content-Type: application/json

{
  "email": "yurisousaenfer@gmail.com",
  "password": "12345678"
}

###

# @name fetch_operators
GET  {{baseurl}}/operators?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name fetch_institutions
GET  {{baseurl}}/institutions?query=ubs
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_institution
POST {{baseurl}}/institutions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "UBS Módulo - 15",
  "cnpj": "11223344551223"
}

###

# @name create_stock
POST {{baseurl}}/stocks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Stock Flora Vida",
  "institutionId": "623bc731-bae7-4ca1-9606-f1e8e56de985"
}

###

# @name fetch_stocks
GET {{baseurl}}/stocks?page=1&institutionsIds=ac96054c-856e-46c0-bdde-7efbe78daba8
Authorization: Bearer {{authToken}}


###

# @name fetch_batches
GET {{baseurl}}/batches
Authorization: Bearer {{authToken}}

###

# @name create_therapeutic_class
POST {{baseurl}}/therapeutic-class
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "name": "antibiótico"
}

###


# @name fetch_therapeutic_classes
GET {{baseurl}}/therapeutic-class?page=1
Authorization: Bearer {{authToken}}

###

# @name fetch_pharmaceutical_form
GET {{baseurl}}/pharmaceutical-form?page=1&query=
Authorization: Bearer {{authToken}}

###

# @name create_pharmaceutical_form
POST {{baseurl}}/pharmaceutical-form
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "name": "xarope"
}


###

# @name create_manufactures
POST {{baseurl}}/manufacturer
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "name": "Aché Laboratórios",
  "cnpj": "12345678901234"
}

###

# @name fetch_manufacturers
GET {{baseurl}}/manufacturer?page=1&cnpj=1
Authorization: Bearer {{authToken}}

###

# @name create_unit-measure
POST {{baseurl}}/unit-measure
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "name": "Caixa",
  "acronym": "CX"
}

###

# @name fetch_units-measures
GET {{baseurl}}/unit-measure?page=1&query=g
Authorization: Bearer {{authToken}}


###

# @name create_pathology
POST {{baseurl}}/pathology
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "name": "sei sdasdasd"
}

###

# @name fetch_pathologies
GET {{baseurl}}/pathologies?page=1
Authorization: Bearer {{authToken}}

###

# @name create_medicine
POST {{baseurl}}/medicine
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "name": "Ibuprofeno",
  "therapeuticClassesIds": ["7e07eebc-4418-4224-a392-10b900abbbe4", "e9b9dfb6-cb92-473b-bd6a-a487cec713e3"]
}

###

# @name fetch_medicines
GET {{baseurl}}/medicines?page=1
Authorization: Bearer {{authToken}}

###

# @name create_medicine_variant
POST {{baseurl}}/medicine-variant
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "medicineId": "35fc9301-0f48-4179-8c18-f2e215a6b30f",
  "dosage": "500",
  "pharmaceuticalFormId": "566b4913-3633-4d59-be16-df60cef5558e",
  "unitMeasureId": "a90fdb0d-bdd6-44b2-ac67-331cbc76f04c"
}

###

# @name fetch_Variants
GET {{baseurl}}/medicines-variants?page=1&query=dip
Authorization: Bearer {{authToken}}


###

# @name create_medicine_entry
POST {{baseurl}}/entry/stock/90295fc4-bf5d-4dcb-9fd6-6ea6fe685c60/medicine-variant/fc89393f-5cce-418b-a9ed-24cc1f0733e8
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "newBatches": [{
    "code": "ABCDE5",
    "expirationDate": "2025-12-01T03:00:00.000Z",
    "manufacturerId": "414998fc-bdaf-4b64-b594-bb68f6bb5084",
    "manufacturingDate": "2025-01-01T03:00:00.000Z",
    "quantityToEntry": 50
  }],
  "movementTypeId": "cf90be5e-92a8-420d-bdaf-583f720cd0a4",
  "entryDate": "2025-01-30T22:30:01.019Z"
}

###

# @name fetch_medicines-entries
GET {{baseurl}}/medicines-entries?page=1&institutionId=1f9d3757-3eb7-4c0f-974b-f59e38b9dc75&medicineVariantId=129b3e69-788f-4d56-9e45-4b22d9dc101b
Authorization: Bearer {{authToken}}

###
# @name create_patient
POST {{baseurl}}/patient
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "name": "John Doe",
  "cpf": "12345678900",
  "sus": "123456789012345",
  "birthDate": "1990-01-01",
  "gender": "M",
  "race": "WHITE",
  "generalRegistration": "123456789",
  "addressPatient": {
    "street": "Elm Street",
    "number": "45B",
    "complement": "Apartment 3A",
    "neighborhood": "Downtown",
    "city": "Springfield",
    "state": "IL",
    "zipCode": "62704"
  },
  "pathologiesIds": [
    "1da8e82c-fb86-4e8e-960c-fb5168ab2ef5"
  ]
}

###
# @name create_dispensation
POST {{baseurl}}/dispensation
Content-Type: application/json
Authorization: Bearer {{authToken}} 

{
  "medicineVariantId": "e446d87c-7727-428d-b090-b3022c440be5",
  "stockId": "7d5e7a16-b09f-44b7-bb3b-acca06ee9b8c",
  "patientId": "d8092162-fa1a-4dcd-aace-cb3cf2eaac8f",
  "batchesStocks": [
    {
      "batchStockId": "2eac69ea-f04e-4817-ad31-862a1bfac2ad",
      "quantity": 20
    }
  ],
  "dispensationDate": "2025-12-01"
}